baseURL = "/"
title = "Fri3d Camp 2024"
description = "Fri3d Camp is een tweejaarlijks gezinsvriendelijk hackercamp."
DefaultContentLanguage= "nl"
sectionPagesMenu = "main"
summaryLength = 10
ignoreFiles = [".+?.bak.md"]
[languages]
	[languages.nl]
		languageName = "Nederlands"
		weight = 1
		languageCode = "nl"
		description = "Fri3d Camp is een tweejaarlijks gezinsvriendelijk hackercamp."
		[languages.nl.params]
			languageDesc = "Deze pagina in het Nederlands"
	[languages.en]
		languageName = "English"
		weight = 2
		languageCode = "en"
		description = "Fri3d Camp is een family friendly hacker camp that takes place every two years."
		[languages.en.params]
			languageDesc = "This page in English"

[params]
	socialimg_square = "/img/site_img_2022_square.jpg"
	socialimg = "/img/site_img_2022.jpg"
	showticker = 0